export const fontColors = {
    gray1: {color: "#B3B3B3"},
    gray2: {color: "#909090"},
    gray3: {color: "#646464"},
    gray4: {color: "#3D3D3D"},
    lightYellow: {color: "#F6C443"},
    darkYellow: {color: "#E69535"},
    lightRed: {color: "#FAD1D1"},
    darkRed: {color: "#EE807C"},
    darkerRed: {color: "#E95750"},
    lightPurple: {color: "#EAD6F3"},
    lightBlue: {color: "#80C9FA"},
    darkBlue: {color: "#53ADF0"},
    lightGreen: {color: "#DEFEBF"},
    darkGreen: {color: "#78C93C"},
    darkerGreen: {color: "#6BA530"},
    white: { color: "#FFFFFF" },
    

};

export const backgroundColors = {
    gray1: { backgroundColor: "#B3B3B3" },
    gray2: { backgroundColor: "#909090" },
    gray3: { backgroundColor: "#646464" },
    gray4: { backgroundColor: "#3D3D3D" },
    lightYellow: { backgroundColor: "#F6C443" },
    darkYellow: { backgroundColor: "#E69535" },
    lightRed: { backgroundColor: "#FAD1D1" },
    darkRed: { backgroundColor: "#EE807C" },
    darkerRed: { backgroundColor: "#E95750" },
    lightPurple: { backgroundColor: "#EAD6F3" },
    lightBlue: { backgroundColor: "#80C9FA" },
    darkBlue: { backgroundColor: "#53ADF0" },
    lightGreen: { backgroundColor: "#DEFEBF" },
    darkGreen: { backgroundColor: "#78C93C" },
    darkerGreen: { backgroundColor: "#6BA530" },
    white: { backgroundColor: "#FFFFFF" },
    homeBlue: { backgroundColor: '#ECF5FB'}
};

export const shadowColors = {
    gray1: { shadowColor: "#B3B3B3" },
    gray2: { shadowColor: "#909090" },
    gray3: { shadowColor: "#646464" },
    gray4: { shadowColor: "#3D3D3D" },
    lightYellow: { shadowColor: "#F6C443" },
    darkYellow: { shadowColor: "#E69535" },
    lightRed: { shadowColor: "#FAD1D1" },
    darkRed: { shadowColor: "#EE807C" },
    darkerRed: { shadowColor: "#E95750" },
    lightPurple: { shadowColor: "#DED1E4" },
    darkPurple: {shadowColor: "#BEB2C2"},
    lightBlue: { shadowColor: "#80C9FA" },
    darkBlue: { shadowColor: "#53ADF0" },
    lightGreen: { shadowColor: "#DEFEBF" },
    darkGreen: { shadowColor: "#78C93C" },
    darkerGreen: { shadowColor: "#6BA530" },
    white: { shadowColor: "#FFFFFF" },
};