export const fontColors = {
    gray1: {color: "#B3B3B3"},
    gray2: {color: "#909090"},
    gray3: {color: "#646464"},
    gray4: {color: "#3D3D3D"},
    lightYellow: {color: "#F6C443"},
    darkYellow: {color: "#E69535"},
    lightRed: {color: "#FAD1D1"},
    darkRed: {color: "#EE807C"},
    darkerRed: {color: "#E95750"},
    lightPurple: {color: "#DED1E4"},
    lightBlue: {color: "#80C9FA"},
    darkBlue: {color: "#53ADF0"},
    lightGreen: {color: "#DEFEBF"},
    darkGreen: {color: "#78C93C"},
    darkerGreen: {color: "#6BA530"},
};

export const backgroundColors = {
    gray1: { backgroundColor: "#B3B3B3" },
    gray2: { backgroundColor: "#909090" },
    gray3: { backgroundColor: "#646464" },
    gray4: { backgroundColor: "#3D3D3D" },
    lightYellow: { backgroundColor: "#F6C443" },
    darkYellow: { backgroundColor: "#E69535" },
    lightRed: { backgroundColor: "#FAD1D1" },
    darkRed: { backgroundColor: "#EE807C" },
    darkerRed: { backgroundColor: "#E95750" },
    lightPurple: { backgroundColor: "#DED1E4" },
    lightBlue: { backgroundColor: "#80C9FA" },
    darkBlue: { backgroundColor: "#53ADF0" },
    lightGreen: { backgroundColor: "#DEFEBF" },
    darkGreen: { backgroundColor: "#78C93C" },
    darkerGreen: { backgroundColor: "#6BA530" },
};